name: Build APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build Phone Debug APK
        run: ./gradlew :phone:assembleDebug

      - name: Upload Phone APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jellycine-phone-debug-apks
          path: phone/build/outputs/apk/debug/*.apk

      - name: Build TV Debug APK
        run: ./gradlew :tv:assembleDebug

      - name: Upload TV APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jellycine-tv-debug-apks
          path: tv/build/outputs/apk/debug/*.apk
